import os
import requests
import streamlit as st
import pandas as pd
import plotly.express as px

API_BASE = os.getenv("ENERGY_API_BASE", "http://localhost:8000").rstrip("/")

st.header("🔮 Load Forecast")
st.caption("Forecast generated by backend predictive model (API-only).")

# User selects forecast horizon
horizon = st.slider(
    "Forecast horizon (hours)",
    min_value=6,
    max_value=72,
    value=24,
    step=6,
)

# Call backend forecast endpoint
url = f"{API_BASE}/forecast"

try:
    response = requests.get(
        url,
        params={"region": "DE", "horizon": horizon},
        timeout=30,
    )
except Exception as e:
    st.error(f"Could not reach backend API: {e}")
    st.stop()

if response.status_code != 200:
    st.error(f"API error {response.status_code}: {response.text[:300]}")
    st.stop()

data = response.json()

if not data:
    st.warning(
        "Forecast not available yet.\n\n"
        "This means the backend does not yet have enough historical "
        "hourly load + weather data to train the model.\n\n"
        "Trigger ingestion or wait for scheduled updates."
    )
    st.stop()

# Convert to DataFrame
df = pd.DataFrame(data)
df["ts"] = pd.to_datetime(df["ts"])
df = df.sort_values("ts")

# Plot forecast
fig = px.line(
    df,
    x="ts",
    y="yhat",
    title=f"Electricity Load Forecast (next {horizon} hours)",
    labels={"ts": "Time", "yhat": "Load (MW)"},
)
st.plotly_chart(fig, use_container_width=True)

# Show forecast table
st.subheader("Forecast values")
st.dataframe(df, use_container_width=True)
